image: Visual Studio 2017

environment:
  # For debugging: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  # APPVEYOR_RDP_PASSWORD: <your_password>

  matrix:
    - PYTHON_VERSION: 3.5.2
      MINICONDA3: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: 3.6
      MINICONDA3: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: 3.7.2
      MINICONDA3: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

version: '1.0.{build}'

init:
    # Linux containers on windows only supported in premium:
    # https://github.com/appveyor-tests/docker-ce/blob/master/appveyor.yml
    # - docker-switch-linux

cache:
  - '%LOCALAPPDATA%\pip\Cache -> requirements.txt, test_requirements.txt'


install:
  - "set PATH=%MINICONDA%;%MINICONDA3%\\Scripts;%PATH%"
  - conda create --name kedro-viz python=%PYTHON_VERSION% -y
  - activate kedro-viz
  - python -m pip install -U pip
  - choco install make
  - make install-pip-setuptools
  - cd package && pip install -r test_requirements.txt -U

build: false

test_script:
  - behave --verbose
