"""Tests for the inspection adapter ID seam (new Viz-side scheme, Decision D9).

Hermetic: the node list comes from ``baseline/node_id_report.json`` (generated by
``capture_baseline.py``); no Kedro project load required. These tests check the *properties*
of the new scheme, not equality with the old backend IDs (which deliberately changed).
"""

import json
from pathlib import Path

import pytest

from kedro_viz.integrations.kedro import node_ids as ids
from kedro_viz.utils import _hash

BASELINE = Path(__file__).parent / "baseline" / "node_id_report.json"


@pytest.fixture(scope="module")
def task_nodes() -> list[dict]:
    return json.loads(BASELINE.read_text(encoding="utf-8"))["nodes"]


def _task_id(node: dict) -> str:
    return ids.task_node_id(node["snapshot_name"], node["inputs"], node["outputs"])


def test_task_node_id_is_deterministic(task_nodes: list[dict]) -> None:
    for node in task_nodes:
        assert _task_id(node) == _task_id(node)


def test_every_task_node_gets_an_id(task_nodes: list[dict]) -> None:
    """Unlike the old scheme, all nodes resolve — including name!=func nodes."""
    assert all(_task_id(node) for node in task_nodes)


def test_task_node_ids_are_unique(task_nodes: list[dict]) -> None:
    computed = [_task_id(node) for node in task_nodes]
    assert len(set(computed)) == len(computed)


def test_task_node_id_excludes_tags() -> None:
    """Re-tagging a node must not change its ID (tags are not an input)."""
    a = ids.task_node_id("ingestion.company_agg", ["x"], ["y"])
    b = ids.task_node_id("ingestion.company_agg", ["x"], ["y"])
    assert a == b


def test_task_node_id_changes_with_io() -> None:
    base = ids.task_node_id("n", ["a"], ["b"])
    assert base != ids.task_node_id("n", ["a", "c"], ["b"])
    assert base != ids.task_node_id("n", ["a"], ["b", "c"])


def test_task_ids_do_not_collide_with_dataset_ids(task_nodes: list[dict]) -> None:
    task_ids = {_task_id(node) for node in task_nodes}
    dataset_ids = set()
    for node in task_nodes:
        for name in node["inputs"] + node["outputs"]:
            dataset_ids.add(ids.dataset_node_id(name))
    assert task_ids.isdisjoint(dataset_ids)


def test_dataset_node_id_matches_backend_hash() -> None:
    assert ids.dataset_node_id("companies") == _hash("companies")


def test_dataset_node_id_strips_transcoding() -> None:
    assert ids.dataset_node_id("typed_shuttles@pandas1") == ids.dataset_node_id(
        "typed_shuttles@pandas2"
    )


def test_task_node_id_handles_missing_inputs_or_outputs() -> None:
    """A source node (no inputs) and a sink node (no outputs) still get valid, distinct IDs.

    Kedro forbids a node with neither inputs nor outputs, so that case cannot occur.
    """
    source = ids.task_node_id("generator", [], ["out_c"])
    sink = ids.task_node_id("saver", ["in_a"], [])
    assert source and sink
    assert source != sink
