name: Install Kedro and other Python Dependencies
description: Installs Kedro from the main branch and other Python dependencies, then prints the Python version and installed packages.
runs:
  using: composite
  steps:
    - name: Install `uv`
      run: |
        python -m pip install "uv==0.5.4"
      shell: bash
    - name: Install Python dependencies
      run: |-
        uv pip install --system -r package/test_requirements.txt -r demo-project/src/docker_requirements.txt -U
        uv pip install --system git+https://github.com/kedro-org/kedro@main
        # [TODO: Revert kedro-datasets installation after kedro-datasets support for kedro 1.0.0 release]
        if [[ $(python -c "import sys; print(sys.version_info[:2] > (3, 9))") == "True" ]]; then
          uv pip install --system git+https://github.com/kedro-org/kedro-plugins.git@main#subdirectory=kedro-datasets
        fi
      shell: bash
    - name: Echo package versions
      run: |-
        python -V
        pip freeze
      shell: bash
