name: Install Kedro and other Python Dependencies
description: Installs Kedro from the main branch and other Python dependencies, then prints the Python version and installed packages.
runs:
  using: composite
  steps:
    - name: Install `uv`
      run: |
        python -m pip install "uv==0.5.4"
      shell: bash
    - name: Install Python dependencies
      run: |-
        uv pip install --system git+https://github.com/kedro-org/kedro@main
        uv pip install --system -r package/test_requirements.txt -r demo-project/src/docker_requirements.txt -U
      shell: bash
    - name: Echo package versions
      run: |-
        python -V
        pip freeze
      shell: bash
