name: Setup Node.js and Install Dependencies
description: Sets up a specific Node.js version, caches Node modules, and installs Node dependencies.

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '18.20.0'

  package-path:
    description: 'Path to package.json file'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Get NPM Cache Directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Node.js packages
      uses: actions/cache@v2
      with:
        path: "${{ steps.npm-cache-dir.outputs.dir }}"
        key: "${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', inputs.package-path)) }}"
        restore-keys: "${{ runner.os }}-node-"

    - name: Install Node Dependencies
      run: npm install
      shell: bash
