extends: existence
message: "Avoid first-person singular pronouns such as '%s'."
level: warning
nonword: true
tokens:
  - (?<=^|\s)I(?=\s)
  - (?<=^|\s)I,(?=\s)
  - \bI'm\b
  - (?<=\s)[Mm]e\b
  - (?<=\s)[Mm]y\b
  - (?<=\s)[Mm]ine\b