extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: false
level: warning
action:
  name: replace
swap:
  # bad: good
  'acknowledgement': 'acknowledgment'
  'auto-complete': 'autocomplete'
  'a number of': 'few|several|many'
  'and/or': 'and|or|either or'
  'back end': 'backend'
  'bear in mind': 'keep in mind'
  'culprit': 'cause'
  'data set': 'dataset'
  'drill down|drilling down|drill into|drilling into': 'examine|investigate|analyze'
  'figure out': 'determine'
  'fine tune|fine-tune': 'customize|optimize|refine'
  'for the most part': 'generally|usually'
  'front end': 'frontend'
  'highly|very': ''
  'hit': 'click|select'
  'in order to': 'to'
  'keep in mind': 'consider'
  'left up to': 'determined by'
  'leverage': 'use'
  'multi-alert': 'multi alert'
  'Note that': '**Note**:'
  'obviously|obvious': ''
  'on the fly': 'real-time|real time'
  'once': 'after'
  'play a hand': 'influence'
  'please|just': ''
  'easily|easy': ''
  'quickly|quick': ''
  'screen board': 'screenboard'
  'simply|simple': ''
  'stand for': 'represents|means'
  'reenable': 're-enable'
  'run time': 'runtime'
  'refer to|visit': 'see|read|follow'
  'time board': 'timeboard'
  'time series': 'timeseries'
  'toplist': 'top list'
  'tradeoff': 'trade-off'
  'turnkey': 'ready to use'
  'under the hood': ''
  'utilize': 'use'
  'via': 'with|through'
  'visit': 'see|read'
  'webserver': 'web server'
  'web site': 'website'