name: Language Linter and Link checks for Kedro-viz Docs
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
      - '**.md'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          reporter: github-pr-review
  
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Check viz documentation
        run: |
          make check-docs
      - name: Check markdown formatting
        run: |
          make fix-markdownlint
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: --max-concurrency 32 --exclude "@.lycheeignore" site/
          # workingDirectory: package