name: Check links in MkDocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Check viz documentation
        run: |
          make check-docs
