name: Language Linter for Kedro-viz Docs
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
      - '**.md'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          reporter: github-pr-review